name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: xelatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: math.tex
          args: -f -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
